import {MigrationInterface, QueryRunner} from "typeorm";

export class initialStructures1576358930500 implements MigrationInterface {
    name = 'initialStructures1576358930500'

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "facility_logistics" ("id" integer NOT NULL, "facilitySecured" boolean NOT NULL, "preferredFacilityType" character varying NOT NULL, "facilityRequests" character varying NOT NULL, CONSTRAINT "PK_3a28d0e99cd57b8b73e4f5083dd" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "program_information" ("id" integer NOT NULL, "eventName" character varying NOT NULL, "dates" character varying NOT NULL, "staffLead" character varying NOT NULL, "department" character varying NOT NULL, "location" character varying NOT NULL, "country" character varying NOT NULL, "typeWorkforce" boolean NOT NULL, "typeEducation" boolean NOT NULL, "typeMeeting" boolean NOT NULL, "typeSummit" boolean NOT NULL, "typeTradeshow" boolean NOT NULL, "typeEvent" boolean NOT NULL, "typeReception" boolean NOT NULL, "typeOtherEvent" boolean NOT NULL, "whoShouldAttend" character varying NOT NULL, "accountCode" character varying NOT NULL, "budget" integer NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "estimatedAttendance" integer NOT NULL, "eventTime" character varying NOT NULL, "setupByDate" TIMESTAMP NOT NULL, "setupByTime" character varying NOT NULL, "summary" character varying NOT NULL, CONSTRAINT "PK_cbd199126cc95bda2f08e2b786a" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "registration_logistics" ("id" integer NOT NULL, "registrationRequired" boolean NOT NULL, "invitationsRequired" boolean NOT NULL, "badgesRequired" boolean NOT NULL, CONSTRAINT "PK_e135601a17a5999196e3583dc7a" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "submission_status" ("id" integer NOT NULL, "submittedToProgramManager" boolean NOT NULL, "submittedToProgramManagerInitials" character varying NOT NULL, "submittedToProgramManagerDate" TIMESTAMP NOT NULL, "submittedToMeetingsEvents" boolean NOT NULL, "submittedToMeetingsEventsInitials" character varying NOT NULL, "submittedToMeetingsEventsDate" TIMESTAMP NOT NULL, "submittedTrainingInformation" boolean NOT NULL, "submittedTrainingInformationInitials" character varying NOT NULL, "submittedTrainingInformationDate" TIMESTAMP NOT NULL, "submittedToMarketing" boolean NOT NULL, "submittedToMarketingInitials" character varying NOT NULL, "submittedToMarketingDate" TIMESTAMP NOT NULL, "additionalNotes" character varying NOT NULL, CONSTRAINT "PK_300aa8cbecff426e4d260870f9a" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "strategy_alignment" ("id" integer NOT NULL, "mwbEducation" boolean NOT NULL, "mwbStandards" boolean NOT NULL, "mwbGlobalAccessibility" boolean NOT NULL, "mwbEngagement" boolean NOT NULL, "mwbValueProposition" boolean NOT NULL, "mwbWorkforceDevelopment" boolean NOT NULL, "objectives" character varying NOT NULL, "goalPeopleReached" integer NOT NULL, CONSTRAINT "PK_939f3d3bbd4da093897b28cf66f" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "site_requirements" ("id" integer NOT NULL, "breakfast" boolean NOT NULL, "lunch" boolean NOT NULL, "dinner" boolean NOT NULL, "snacks" boolean NOT NULL, "openbar" boolean NOT NULL, "cashbar" boolean NOT NULL, "supportStaff" boolean NOT NULL, "dining" boolean NOT NULL, "av" boolean NOT NULL, "tableTents" boolean NOT NULL, "signage" boolean NOT NULL, "amenities" character varying NOT NULL, "additionalRequests" character varying NOT NULL, "updatedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_5547e11a6f3978fbd409dc0eba4" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "request_form" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "statusId" integer, "programId" integer, "strategyId" integer, "facilityLogisticsId" integer, "registrationLogisticsId" integer, "siteRequirementsId" integer, CONSTRAINT "REL_f8153fcb50ecf9ff106f9a1b5d" UNIQUE ("statusId"), CONSTRAINT "REL_885bc21a0cb45ea5433f644efc" UNIQUE ("programId"), CONSTRAINT "REL_97df959fdf379c720c71add468" UNIQUE ("strategyId"), CONSTRAINT "REL_2f8437fdcde65b753b3abe20f2" UNIQUE ("facilityLogisticsId"), CONSTRAINT "REL_f3da2dfc461e536d2f79815ee3" UNIQUE ("registrationLogisticsId"), CONSTRAINT "REL_a393daed576bbc051e15fbf37b" UNIQUE ("siteRequirementsId"), CONSTRAINT "PK_cdb8b03116451c339db40fb8bcc" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "training_session" ("id" integer NOT NULL, "requestId" integer NOT NULL, "courseTitle" character varying NOT NULL, "courseDescription" character varying NOT NULL, "learningObjectives" character varying NOT NULL, "aptifyCourseId" character varying NOT NULL, "aptifyClassId" character varying NOT NULL, "trainingDates" character varying NOT NULL, "startTime" character varying NOT NULL, "endTime" character varying NOT NULL, "instructor" character varying NOT NULL, "travelNeeded" boolean NOT NULL, "instructorBio" character varying NOT NULL, "ceusAwarded" boolean NOT NULL, "numberOfCeus" integer NOT NULL, "roomLayout" character varying NOT NULL, "classCapacity" integer NOT NULL, "standardMemberPrice" integer NOT NULL, "standardNonMemberPrice" integer NOT NULL, "earlyBirdMemberPrice" integer NOT NULL, "earlyBirdNonMemberPrice" integer NOT NULL, "dicountsAndBundles" character varying NOT NULL, "additionalRequests" character varying NOT NULL, CONSTRAINT "PK_a17a9657ff5a6e048bfd82c4651" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" ADD CONSTRAINT "FK_f8153fcb50ecf9ff106f9a1b5d9" FOREIGN KEY ("statusId") REFERENCES "submission_status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" ADD CONSTRAINT "FK_885bc21a0cb45ea5433f644efc7" FOREIGN KEY ("programId") REFERENCES "program_information"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" ADD CONSTRAINT "FK_97df959fdf379c720c71add4680" FOREIGN KEY ("strategyId") REFERENCES "strategy_alignment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" ADD CONSTRAINT "FK_2f8437fdcde65b753b3abe20f27" FOREIGN KEY ("facilityLogisticsId") REFERENCES "facility_logistics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" ADD CONSTRAINT "FK_f3da2dfc461e536d2f79815ee39" FOREIGN KEY ("registrationLogisticsId") REFERENCES "registration_logistics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" ADD CONSTRAINT "FK_a393daed576bbc051e15fbf37bc" FOREIGN KEY ("siteRequirementsId") REFERENCES "site_requirements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "request_form" DROP CONSTRAINT "FK_a393daed576bbc051e15fbf37bc"`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" DROP CONSTRAINT "FK_f3da2dfc461e536d2f79815ee39"`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" DROP CONSTRAINT "FK_2f8437fdcde65b753b3abe20f27"`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" DROP CONSTRAINT "FK_97df959fdf379c720c71add4680"`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" DROP CONSTRAINT "FK_885bc21a0cb45ea5433f644efc7"`, undefined);
        await queryRunner.query(`ALTER TABLE "request_form" DROP CONSTRAINT "FK_f8153fcb50ecf9ff106f9a1b5d9"`, undefined);
        await queryRunner.query(`DROP TABLE "training_session"`, undefined);
        await queryRunner.query(`DROP TABLE "request_form"`, undefined);
        await queryRunner.query(`DROP TABLE "site_requirements"`, undefined);
        await queryRunner.query(`DROP TABLE "strategy_alignment"`, undefined);
        await queryRunner.query(`DROP TABLE "submission_status"`, undefined);
        await queryRunner.query(`DROP TABLE "registration_logistics"`, undefined);
        await queryRunner.query(`DROP TABLE "program_information"`, undefined);
        await queryRunner.query(`DROP TABLE "facility_logistics"`, undefined);
    }

}
